// Code generated by "stringer -type=EntityID"; DO NOT EDIT.

package espgohome

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UndefinedEntity-0]
	_ = x[BinarySensor-1]
	_ = x[Cover-2]
	_ = x[Fan-3]
	_ = x[Light-4]
	_ = x[Sensor-5]
	_ = x[Switch-6]
	_ = x[TextSensor-7]
	_ = x[Camera-8]
	_ = x[Climate-9]
}

const _EntityID_name = "UndefinedEntityBinarySensorCoverFanLightSensorSwitchTextSensorCameraClimate"

var _EntityID_index = [...]uint8{0, 15, 27, 32, 35, 40, 46, 52, 62, 68, 75}

func (i EntityID) String() string {
	if i < 0 || i >= EntityID(len(_EntityID_index)-1) {
		return "EntityID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntityID_name[_EntityID_index[i]:_EntityID_index[i+1]]
}
