// Code generated by "stringer -type=MessageID"; DO NOT EDIT.

package espgohome

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HelloRequestID-1]
	_ = x[HelloResponseID-2]
	_ = x[ConnectRequestID-3]
	_ = x[ConnectResponseID-4]
	_ = x[DisconnectRequestID-5]
	_ = x[DisconnectResponseID-6]
	_ = x[PingRequestID-7]
	_ = x[PingResponseID-8]
	_ = x[DeviceInfoRequestID-9]
	_ = x[DeviceInfoResponseID-10]
	_ = x[ListEntitiesRequestID-11]
	_ = x[ListEntitiesDoneResponseID-19]
	_ = x[SubscribeStatesRequestID-20]
	_ = x[ListEntitiesBinarySensorResponseID-12]
	_ = x[BinarySensorStateResponseID-21]
	_ = x[ListEntitiesCoverResponseID-13]
	_ = x[CoverStateResponseID-22]
	_ = x[CoverCommandRequestID-30]
	_ = x[ListEntitiesFanResponseID-14]
	_ = x[FanStateResponseID-23]
	_ = x[FanCommandRequestID-31]
	_ = x[ListEntitiesLightResponseID-15]
	_ = x[LightStateResponseID-24]
	_ = x[LightCommandRequestID-32]
	_ = x[ListEntitiesSensorResponseID-16]
	_ = x[SensorStateResponseID-25]
	_ = x[ListEntitiesSwitchResponseID-17]
	_ = x[SwitchStateResponseID-26]
	_ = x[SwitchCommandRequestID-33]
	_ = x[ListEntitiesTextSensorResponseID-18]
	_ = x[TextSensorStateResponseID-27]
	_ = x[SubscribeLogsRequestID-28]
	_ = x[SubscribeLogsResponseID-29]
	_ = x[SubscribeHomeassistantServicesRequestID-34]
	_ = x[HomeassistantServiceResponseID-35]
	_ = x[SubscribeHomeAssistantStatesRequestID-38]
	_ = x[SubscribeHomeAssistantStateResponseID-39]
	_ = x[HomeAssistantStateResponseID-40]
	_ = x[GetTimeRequestID-36]
	_ = x[GetTimeResponseID-37]
	_ = x[ListEntitiesServicesResponseID-41]
	_ = x[ExecuteServiceRequestID-42]
	_ = x[ListEntitiesCameraResponseID-43]
	_ = x[CameraImageResponseID-44]
	_ = x[CameraImageRequestID-45]
	_ = x[ListEntitiesClimateResponseID-46]
	_ = x[ClimateStateResponseID-47]
	_ = x[ClimateCommandRequestID-48]
}

const _MessageID_name = "HelloRequestIDHelloResponseIDConnectRequestIDConnectResponseIDDisconnectRequestIDDisconnectResponseIDPingRequestIDPingResponseIDDeviceInfoRequestIDDeviceInfoResponseIDListEntitiesRequestIDListEntitiesBinarySensorResponseIDListEntitiesCoverResponseIDListEntitiesFanResponseIDListEntitiesLightResponseIDListEntitiesSensorResponseIDListEntitiesSwitchResponseIDListEntitiesTextSensorResponseIDListEntitiesDoneResponseIDSubscribeStatesRequestIDBinarySensorStateResponseIDCoverStateResponseIDFanStateResponseIDLightStateResponseIDSensorStateResponseIDSwitchStateResponseIDTextSensorStateResponseIDSubscribeLogsRequestIDSubscribeLogsResponseIDCoverCommandRequestIDFanCommandRequestIDLightCommandRequestIDSwitchCommandRequestIDSubscribeHomeassistantServicesRequestIDHomeassistantServiceResponseIDGetTimeRequestIDGetTimeResponseIDSubscribeHomeAssistantStatesRequestIDSubscribeHomeAssistantStateResponseIDHomeAssistantStateResponseIDListEntitiesServicesResponseIDExecuteServiceRequestIDListEntitiesCameraResponseIDCameraImageResponseIDCameraImageRequestIDListEntitiesClimateResponseIDClimateStateResponseIDClimateCommandRequestID"

var _MessageID_index = [...]uint16{0, 14, 29, 45, 62, 81, 101, 114, 128, 147, 167, 188, 222, 249, 274, 301, 329, 357, 389, 415, 439, 466, 486, 504, 524, 545, 566, 591, 613, 636, 657, 676, 697, 719, 758, 788, 804, 821, 858, 895, 923, 953, 976, 1004, 1025, 1045, 1074, 1096, 1119}

func (i MessageID) String() string {
	i -= 1
	if i >= MessageID(len(_MessageID_index)-1) {
		return "MessageID(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageID_name[_MessageID_index[i]:_MessageID_index[i+1]]
}
